### ISSUE TITLE
when will the model weights(generator_background checkpoint and layout checkpoint) be released?

### ISSUE THREAD

**Issue by mengxinZHANG** [whaohan/desigen#2]

**Comment by sandy-ssdut** [comment]
Same question~

**Comment by whaohan** [comment]
To prevent potential copyright issues, we currently have no plans to release our model checkpoints. To reproduce our experiments, you can download and process the data with the provided toolkits and retrain the models easily.

**Comment by aaghawaheed** [comment]
@sandy-ssdut, @mengxinZHANG, have you tried to train, are you able to generate the same results as mentioned in the paper. Thanks
