### ISSUE TITLE
关于显著性mask的问题

### ISSUE THREAD

**Issue by ZcyMonkey** [whaohan/desigen#3]
请问您在处理显著性mask的时候，是以白色来表示显著性区域，黑色表示非显著性区域的吗？
如果是这样，那为什么在训练的时候，代码里attention乘以的是(1 - saliency)，而不是直接乘以saliency呢？

**Comment by whaohan** [comment]
1. Yes. When processing saliency maps, we use white color (1) to represent the salient regions, and black color (0) to represent the non-salient regions.
2. The attention weights of non-salient regions should be lowered, while the weights of salient regions should be maintained to keep the original context (see more details on paper Section 4.2). Therefore, we only select the non-salient regions (1 - saliency) and reduce its cross attention activation to preserve more space for background images. We don't modify the attention on salient regions to keep the generation performance.
