### ISSUE TITLE
questons about layout region of the background training dataset

### ISSUE THREAD

**Issue by qhanson** [whaohan/desigen#5]
How to check the layout regions in metadata.jsonl?
I resize the image to (224, 224) and draw the result based on (x,y,w,h) defintion. Seems the region does not align the background?
Do I make any mistake to understand the metadata.jsonl in the training dataset?

**Comment by qhanson** [comment]
<img width="1555" alt="image" src="https://github.com/whaohan/desigen/assets/42370796/51edc156-450b-4216-b6ed-fe4fd1d5168e">
Try to draw the regions in the resize 224, not all regions are good  for text layout.

**Comment by whaohan** [comment]
The data collected from the internet has a range of quality levels, and it is quite challenging to balance the quantity and quality of the data. In our experiment, we found that the current filtered data is good enough to train a reasonable layout generator although some unsatisfying layouts. Feel free to conduct further data filtering based on the Occlusion metric implemented [here](https://github.com/whaohan/desigen/blob/5fff520cf37254f1805d1cb4fbc3e2bb685e3442/layout/trainer.py#L176) by selecting a more strict threshold.

**Comment by qhanson** [comment]
Thanks, it solved my concern about the understanding of the dataset.

**Comment by aaghawaheed** [comment]
@qhanson, are you able to generate the weights for background and layout.
