### ISSUE TITLE
'/data/processed/saliency_e'文件夹是什么

### ISSUE THREAD

**Issue by jinqia0** [whaohan/desigen#8]
请问`background/train_background.py`中的第337行`self.saliency_root = Path('/data/processed/saliency_e')`中`'/data/processed/saliency_e'`文件夹是在哪一步产生的？我下载了数据并运行scripts里的脚本后并没有得到这个文件夹，该文件夹应该存放的内容是什么？
从`BackgroundDataset`类的代码中
```
def __getitem__(self, index):
    item = json.loads(self.instance_prompt[index % self.num_instance_images])
    example = {}
    instance_image = Image.open(self.instance_data_root / item['file_name'])
    if not instance_image.mode == "RGB":
        instance_image = instance_image.convert("RGB")
    example["instance_images"] = self.image_transforms(instance_image)
    saliency_image = Image.open(self.saliency_root / item['file_name'])
```
看到它与`background/train`内的文件应与`background/train/metadata.jsonl`对应，但`background_train.json`与`background/train/metadata.jsonl`中filename也不对应，应该怎么理解它们的关系？

**Comment by TrNgTinh** [comment]
Have you solved it yet?

**Comment by whaohan** [comment]
Hi,

`/data/processed/saliency_e` is the saliency files processed from the background images. You can get it from the [script](https://github.com/whaohan/desigen/blob/main/scripts/saliency.py). You can also process the background images with any other saliency detector.

**Comment by jinqia0** [comment]
> Hi,
> 
> `/data/processed/saliency_e` is the saliency files processed from the background images. You can get it from the [script](https://github.com/whaohan/desigen/blob/main/scripts/saliency.py). You can also process the background images with any other saliency detector.

I didn't see words like 'processed' or 'saliency_e' in the  [script](https://github.com/whaohan/desigen/blob/main/scripts/saliency.py), so I'm not quite sure what `/data/processed/saliency_e` contains. Is it a copy of `SALIENCY = r'data/saliency/` in the code? I think maybe you should add some instructions to make it more clear.

**Comment by whaohan** [comment]
Thanks for your suggestion. I have updated the code with more clear instructions.
