### ISSUE TITLE
AttributeError: 'UNet2DConditionModel' object has no attribute 'module'. Did you mean: 'modules'

### ISSUE THREAD

**Issue by TrNgTinh** [whaohan/desigen#9]
I am training the background, and currently, I am encountering an issue `AttributeError: 'UNet2DConditionModel' object has no attribute 'module'. Did you mean: 'modules'` at this line in the file:

```
with accelerator.accumulate(unet):
                if args.with_spatial_loss:
                    unet.module.attn_store.clear()
```
[this line](https://github.com/whaohan/desigen/blob/main/background/train_background.py#L857)

I am not sure if this is due to a wrong library or a misconfiguration. Can you help me?

**Comment by whaohan** [comment]
Hi,

If you use only 1 GPU for training, just remove `.module` in this line, i.e., `unet.attn_store.clear()`.

**Comment by TrNgTinh** [comment]
Thank you very much, it worked. Haha. I found it strange because yesterday, when I ran it with 2 GPUs, there was no error. Today, I switched to a new server and ran it with only 1 GPU, and encountered the error. So I was quite confused. Thank you very much for your help. @whaohan
